Use "struct ctl_table" to make code compile on recent kernels
With the current code at "static ctl_table", the code will fail to
compile on Linux 3.18 (and maybe younger kernels).

/var/lib/dkms/vrouter/1.20/build/linux/vrouter_mod.c:2133:1: error:
    unknown type name ‘ctl_table’
 static ctl_table vrouter_table[] =

This can easily avoided by using "static struct ctl_table", which is
what this commit does.

Change-Id: Icb2e9aac2fade642d754cccb7d33fd15867665e2